/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package android.content.pm;

import android.content.ComponentName;
import android.content.LocusId;
import android.os.Build;
import android.os.Parcel;
import android.os.Parcelable;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.RequiresApi;

import java.util.List;

@RequiresApi(api = Build.VERSION_CODES.N_MR1)
public final class ShortcutQueryWrapper extends LauncherApps.ShortcutQuery implements Parcelable {

    public ShortcutQueryWrapper(LauncherApps.ShortcutQuery query) {
        throw new RuntimeException("Stub!");
    }

    public long getChangedSince() {
        throw new RuntimeException("Stub!");
    }

    @Nullable
    public String getPackage() {
        throw new RuntimeException("Stub!");
    }

    @Nullable
    public List<LocusId> getLocusIds() {
        throw new RuntimeException("Stub!");
    }

    @Nullable
    public List<String> getShortcutIds() {
        throw new RuntimeException("Stub!");
    }

    @Nullable
    public ComponentName getActivity() {
        throw new RuntimeException("Stub!");
    }

    public int getQueryFlags() {
        throw new RuntimeException("Stub!");
    }

    // Code below generated by codegen v1.0.14.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/frameworks/base/core/java/android/content/pm/ShortcutQueryWrapper.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off
    public ShortcutQueryWrapper() {
        // onConstructed(); // You can define this method to get a callback
    }

    @Override
    public String toString() {
        throw new RuntimeException("Stub!");
    }

    @Override
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        throw new RuntimeException("Stub!");
    }

    @Override
    public int describeContents() {
        throw new RuntimeException("Stub!");
    }

    /* package-private */ ShortcutQueryWrapper(@NonNull Parcel in) {
        throw new RuntimeException("Stub!");
    }


    public static final @NonNull Parcelable.Creator<ShortcutQueryWrapper> CREATOR
            = new Parcelable.Creator<ShortcutQueryWrapper>() {
        @Override
        public ShortcutQueryWrapper[] newArray(int size) {
            throw new RuntimeException("Stub!");
        }
        @Override
        public ShortcutQueryWrapper createFromParcel(@NonNull Parcel in) {
            throw new RuntimeException("Stub!");
        }
    };

    @Deprecated
    private void __metadata() {}
    //@formatter:on
    // End of generated code
}